// src/config.js

export const CAR_SETTINGS = {
  RPM_IDLE: 750,
  RPM_MAX: 8000,
  RPM_OVERTAKE_BOOST: 2000,
  OVERTAKE_DURATION_MS: 8000,
  OVERTAKE_BATTERY_COST: 20,
  PIT_STOP_DURATION_MS: 4000,
  SIMULATION_TICK_MS: 5000,
  FUEL_CONSUMPTION_RATE: {
    LEAN: 0.2,
    STANDARD: 0.5,
    RICH: 1.2,
  },
  BATTERY_RECHARGE_RATE: 0.2,
};
